resources:
  - backend-deploy.yaml
  - backend-svc.yaml
  - namespace-backend.yaml
  - configmap-backend-env.yaml
  - backend-secret.yaml
images:
  - name: beming/chat-irumae-backend
    newTag: d0b809d22e2ac97d2fd76e432c611ec8a609a81e
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
