resources:
  - backend-deploy.yaml
  - backend-svc.yaml
  - namespace-backend.yaml
  - configmap-backend-env.yaml
  - backend-secret.yaml
images:
  - name: beming/chat-irumae-backend
    newTag: 6a26c0bdb4d43e7fd5e2e499a9fff05fe054c98f
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
