resources:
  - backend-deploy.yaml
  - backend-svc.yaml
  - namespace-backend.yaml
  - configmap-backend-env.yaml
  - backend-secret.yaml
images:
  - name: beming/chat-irumae-backend
    newTag: cc3034c77c5dc10727d9a12883f620d59ba73552
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
