resources:
  - backend-deploy.yaml
  - backend-svc.yaml
  - namespace-backend.yaml
  - configmap-backend-env.yaml
  - backend-secret.yaml
images:
  - name: beming/chat-irumae-backend
    newTag: ab083dfb8a68874801c174ef2e6ed79d6dee9203
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
