resources:
  - backend-deploy.yaml
  - backend-svc.yaml
  - namespace-backend.yaml
  - configmap-backend-env.yaml
  - backend-secret.yaml
images:
  - name: beming/chat-irumae-backend
    newTag: 07ab92500bb98e233584978ed8b97c1563bceb9d
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
