resources:
  - backend-deploy.yaml
  - backend-svc.yaml
  - namespace-backend.yaml
  - configmap-backend-env.yaml
  - backend-secret.yaml
images:
  - name: beming/chat-irumae-backend
    newTag: 17b11d4551aefb25f1e9cd3b370c5151f386a469
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
