resources:
  - frontend-deploy.yaml
  - frontend-svc.yaml
  - namespace-frontend.yaml
  - configmap-frontend-env.yaml
  - secret-frontend-env.yaml
images:
  - name: beming/chat-irumae-frontend
    newTag: 277205b305350b958dfe29305053fd81717cc8fd
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
