resources:
  - frontend-deploy.yaml
  - frontend-svc.yaml
  - namespace-frontend.yaml
  - configmap-frontend-env.yaml
  - secret-frontend-env.yaml
images:
  - name: beming/chat-irumae-frontend
    newTag: e2e5550aa57f13fc3408a8d9bf1f3d112759136d
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
